### ISSUE TITLE
parse loops infinitely and prevents SIGNAL-based timeouts

### ISSUE THREAD

**Issue by halfak** [earwig/mwparserfromhell#206]
I've run into a revision in Spanish Wikipedia that causes `parse()` in version 0.5.1 to loop infinitely *and* prevent signal-based timeouts from interrupting the call after a timeout.  The same revision causes an infinite loop in `parse()` of 0.5.0, but it can be interrupted with a signal-based timeout.  

See code for reproducing the issue here: 
```
import mwapi
import stopit
from mwparserfromhell import __version__, parse

print("mwparserfromhell version:", __version__)

result = mwapi.Session("https://es.wikipedia.org", user_agent="mwp test").get(
    action="query", prop="revisions", revids=111186880, rvprop=["content"],
    rvslots=["main"], formatversion=2)
wikitext = result['query']['pages'][0]['revisions'][0]['slots']['main']['content']

# Try to parse, but set a signal-based timeout for 5 seconds
with stopit.SignalTimeout(5) as to_ctx_mgr:
    result = parse(wikitext)

# OK, let's check what happened
if to_ctx_mgr.state == to_ctx_mgr.EXECUTED:
    print("Everything executed fine")
else:  # to_ctx_mgr.state == to_ctx_mgr.TIMED_OUT:
    print("A timeout happend")
```

**Comment by halfak** [comment]
It's also worth noting that the 0.5.1 run of this script will result in a process that cannot be killed with "kill -15 <pid>"   I've only been able to kill it with "kill -9 <pid>".

**Comment by halfak** [comment]
I've just run some tests on different distributions.  I've confirmed that the above demo script works with the signal timeout in v0.5 with Ubuntu 16.04.  But the signal timeout doesn't work in v0.5 in Debian Jessie 9.3.  

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch
```

It looks like this is because the compile for 0.5.0 fails on Ubuntu 16.04 and there's a fallback to a pure python implementation.  

```
    mwparserfromhell/parser/ctokenizer/common.h:29:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Falling back to pure Python mode.
```

The compile for 0.5.1 did not fail for some reason.

**Comment by legoktm** [comment]
If Python.h is missing, that means you need to install the `python3-dev` package.

**Comment by halfak** [comment]
Right.  I've installed that and tested and now 0.5.0 gets stuck and is not interrupt-able too.

**Comment by Riamse** [comment]
What's the content of the page that it hangs on?

**Comment by akosiaris** [comment]
That would be https://es.wikipedia.org/w/index.php?title=Usuario:Danielalfredo/Taller&oldid=111186880&action=raw

Something of note to add to this (and that actually caused me pain in trying to reproduce this) is that adding a single newline character (`\n`, utf8 hex `0a`) at the end of file causes this to be parse-able (in a pretty long time on my tests, > 3secs but still parse-able)

**Comment by earwig** [comment]
This is perplexing—I can't find that revision of that page. I only see 111245451 and 111245482, and both of them parse fine, as far as I can tell.

**Comment by earwig** [comment]
There are two issues here: the trapping-SIGINT issue and the parsing issue.

The former fortunately has an easy fix. Python traps SIGINT and some other signals so it can convert them into Python exceptions, but since we're getting stuck in C code, we never have a chance for that to bubble out. We were simply missing a call to [PyErr_CheckSignals](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals). This is now fixed in 6de7d41.

I'm still looking into the latter.

**Comment by earwig** [comment]
@halfak Apologies for the delay, I hoped to get it out earlier. A bit swamped at the moment, but will try to do it soon. BTW, you can set `mparserfromhell.parser.use_c = False` as an emergency fix to avoid C if that is at all useful.

**Comment by halfak** [comment]
Hi @earwig.  We've worked out that in some cases, the pure-python parser is too slow, so we're still waiting on a new release for our deployment.  Do you think you could get it out soon?

**Comment by earwig** [comment]
Apologies again. I’ll do this tonight when I get home from work.

**Comment by earwig** [comment]
It's still my job to maintain the parser, just not my day job :P

OK, I released 0.5.2. I'll leave this issue open until I fix the table parsing issue.

**Comment by earwig** [comment]
Finally figured this out. Of course, the solution ended up being somewhat trivial.
